export enum AdminErrorMessage {
  PartnerNotFound = "Partner not found",
  ProductNotFound = "Product not found",
  OrderNotFound = "Order not found",
  CategoryNotFound = "Category not found",
  InviteNotFound = "Admin invite not found",
  AlreadyReviewed = "The review has already been completed",
  OrderChanged = "The order status has already changed",
  InviteChanged = "The admin invite has already changed",
  RejectionReasonRequired = "Rejection reason must be between 1 and 500 characters",
  InvalidCursor = "Invalid admin cursor",
  InvalidDate = "Invalid date filter",
  InvalidCategory = "Invalid category input",
  DuplicateCategorySlug = "Category slug already exists",
  CategoryCycle = "Category hierarchy cannot contain a cycle",
  CategoryHasActiveChildren = "Category has active child categories",
  CategoryHasPublicProducts = "Category has public products",
  InviteEmailAlreadyRegistered = "A user with this email already exists",
  InviteEmailFailed = "Admin invite email could not be sent",
  InvalidOrExpiredInvite = "Invalid or expired admin invite",
  AuthenticationRequired = "Authentication required",
}
