export const ALLOWED_TRANSITIONS: Record<string, string[]> = {
  PAYMENT_PENDING: ["FAILED", "CANCELLED"],
  PAID: ["FULFILLING", "CANCELLED"],
  FULFILLING: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: [],
  FAILED: [],
};
